---

palava_signaltower_install_dir: /srv/signaltower-staging
palava_signaltower_log_dir: /var/log/signaltower-staging
palava_environment: staging

palava_signaltower_autostart: yes
palava_signaltower_port: 4234 # overwrite signaltower role default
